# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: test-policies

generatorOptions:
  disableNameSuffixHash: true

# list of Resource Config to be Applied
resources:
  - namespace.yaml
  - git-ca.yaml
  - channel.yaml
  - subscription.yaml


