apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: stable
  name: demo-stable-policies-sub
  namespace: test-policies
spec:
  channel: test-policies/stable-policies-chan
  placement:
    local: true
